### ISSUE TITLE
Python Port Date?

### ISSUE THREAD

**Issue by DonatasTamosauskas** [AinoraZ/EFCore.IncludeBuilder#21]
### Description
Currently the library only supports the C# ecosystem. This is an issue as python is objectively better with faster compilation, better type safety and wider adoption within enterprises.

### Current behaviour 
When searching for [IncludeBuilder](https://github.com/AinoraZ/EFCore.IncludeBuilder) or Entity Framework in Python Package Index nothing shows up. Install with ```pip install IncludeBuilder``` fails.

### Expected behaviour
```pip install IncludeBuilder``` successfully installs the package and Entity Framework is ported to Python too.

### Workarounds
None found so far, therefore this is urgent! When can I expect a fix for this?

**Comment by AinoraZ** [comment]
Thank you for opening an issue. While I would love the option to be able to use Entity Framework on other languanges, sadly such porting endeavours are outside the scope for this small project 😄.
